name: Build and Release APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web application
      run: npm run build
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: cd android && ./gradlew assembleDebug
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
      
    - name: Get commit hash
      id: commit
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Rename APK with timestamp
      run: |
        mkdir -p artifacts
        cp android/app/build/outputs/apk/debug/app-debug.apk artifacts/Muhasabah-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}.apk
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Muhasabah-APK-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
        path: artifacts/*.apk
        retention-days: 30
        
    - name: Create Release (on main branch push)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      continue-on-error: true
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
        name: Auto Release ${{ steps.date.outputs.date }}
        body: |
          🚀 **Automated Release - Muhasabah**
          
          **Changes in this release:**
          - Latest updates from commit ${{ steps.commit.outputs.hash }}
          - Built on ${{ steps.date.outputs.date }}
          
          **Download:**
          - 📱 Android APK: Muhasabah-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}.apk
          
          **Installation:**
          1. Download the APK file
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK
          
          **About Muhasabah:**
          A spiritual reflection and self-accountability app to help with daily Islamic practices and personal development.
          
          ---
          *This release was automatically generated by GitHub Actions*
        files: artifacts/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release (on manual release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
